timezone: Asia/Hong_Kong
url: https://eric15342335.github.io/desn9002-education-platform
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: Edbridge | Building Pathways to Global Success | Connecting global students with Hong Kong's educational opportunities through digital resources, expert matching, and community engagement.

author:
  name: Cheng Ho Ming, Eric
  email: eric310@connect.hku.hk
  url: https://eric15342335.github.io/desn9002-education-platform
  github: eric15342335
  twitter: eric15342335

social:
  name: eric15342335
  links:
    - https://github.com/eric15342335
    - https://www.linkedin.com/in/eric15342335/
    - https://www.instagram.com/ericcheng0310/
    - https://x.com/eric15342335/
    - https://www.binance.com/en/square/profile/eric15342335
    - https://steamcommunity.com/id/eric15342335

twitter:
  username: eric15342335
  card: summary

webmaster_verifications:
  google: nKhf3k5Ab3PBY31uGwwA-9csMaoM8j2T96heECb4RuM

theme: null
